arkounay_quick_admin_generator:
    title: '__project_name__'
    #dashboard_route_redirection: 'qag.news'
    theme:
        default: 'light'
        allow_switch: false
when@dev:
    arkounay_quick_admin_generator:
        allow_form_resubmit: true